config/routes.rb
Reedit::Application.routes.draw do
  resources :links do
	collection do
		get 'submissions'
	end
  end
	

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  def submissions
	#@links = Link.find_all
	ordering = params[:order] || 'hot'
	order = case ordering
		when 'hot' then 'points DESC'
		when 'new' then 'created_at DESC'
		end
#	@link_pages, @links = paginate :links, :order=> order, :per_page => 20
	@links = Link.paginate(:page => params[:page], :per_page => 20)
	@hearder_text = case ordering
			when 'hot' then 'Top rated submissions'
			when 'new' then 'Latest submissions'
			end
  end

  def modify_points
	@link = Link.find(params[:id])
	@link.update_attribute :points, @link.points + params[:by].to_i if params[:by] =~ /[+|-]?1/
	render_text @link.points
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reedit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>URL:</b>
  <%= @link.url %>
</p>

<p>
  <b>Description:</b>
  <%= @link.description %>
</p>
<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/links/submissions.html.erb
<%= javascript_include_tag :defaults %>

<h1><%= @hearder_text%></h1>
<%= link_to "HOT", {:action => 'submissions', :order => 'hot'} %> |
<%= link_to "NEW", {:action => 'submissions', :order => 'new'} %> |
<%= link_to 'Add new link', :action => 'new'%>

<% unless @links.nil? %>
<table>
<% for link in @links %>
	<tr valign = 'top'>
		<td>
		<%= link_to  "UP", :url => {:action => 'modify_points',
					 :id => link.id,
					 :by => 1,
					:remote => true},
					 :update => "link" + link.id.to_s %>

		</td>
		<td>
		<%= link_to "DOWN", :url => {:action => 'modify_points',
					 :id => link.id,
					 :by => -1,
					:remote => true},
					 :update => "link" + link.id.to_s %>

		</td>
		<td>
		<b><a href="<%= link.url %>"> <%= link.description %> </a></b>
		(<%= if link.url =~ /(:\/\/)[^\/]*/ then $2 else "wrong URL" end %>)</br>
		<span id = "link<%= link.id.to_s %>"> <%= link.points %></span>
		points 
posted <%= time_ago_in_words link.create_at %> ago
		</td>
<% end %>
</table>
<% else %>
No submisssions yet
<% end %>
<%= will_paginate @links %>